services:
  theweb-api:
    image: ivoraedts/da-vue-theweb-api:latest
    ports:
      # <Host Port>:<Container Port>
      - "5160:8080"
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - docker-da-vue

  theweb-ui:
    image: ivoraedts/da-vue-theweb-ui:latest
    ports:
    # <Host Port>:<Container Port>
      - "3000:80"
    depends_on:
      - theweb-api
    networks:
      - docker-da-vue

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d DaVueDb -U user-name -h localhost -p 5432"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    container_name: docker-da-vue.postgres
    #command: postgres -c max_connections=100
    volumes:  
    # This fix applies to version 18 and later. before it could mount to /var/lib/postgresql/data
    # This fix applies to version 18 and later: mount to /var/lib/postgresql/docker works, but does not persist
      - ./docker/pgdata:/var/lib/postgresql
    networks:
      - docker-da-vue
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    ports:
      # <Host Port>:<Container Port>
      - "5433:5432"

  adminer:
    image: adminer:latest
    container_name: docker-da-vue.adminer    
    networks:
      - docker-da-vue
    ports:
      # <Host Port>:<Container Port>
      - "8081:8080"

networks:
  docker-da-vue:
    driver: bridge
